import = [
"alacritty-theme/themes/gruvbox_dark.toml",
]

[shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[font]
size = 20
normal = { family = "FantasqueSansM Nerd Font", style = "Regular" }
bold = { family = "FantasqueSansM Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono NF", style = "Italic" }


[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9
startup_mode = "Maximized"

[window.padding]
x = 18
y = 16

[window.position]
x = 5
y = 5

[keyboard]
bindings = [
{ key = "F12", action = "ToggleFullscreen" }
]
