# format = '$all$directory$character'
add_newline = false
# A minimal left prompt
format = """$directory$character"""
# palette = "catppuccin_mocha"
# move the rest of the prompt to the right
right_format = """$all"""

# [directory]
# truncation_length = 2
# truncation_symbol = '…/'
# disabled = true

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'


[golang]
format = '[ $version](bold cyan) '
